name: Sync Upstream

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add Upstream Repo
        run: git remote add upstream https://github.com/pigzillaaaaa/daddylive.git

      - name: Fetch and Merge Upstream
        run: |
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories --no-edit || true
          git push origin main
